### ISSUE TITLE
Cannot build via bazel without major system modifications

### ISSUE THREAD

**Issue by MarkSchmitt** [eclipse-score/communication#3]
On a Ubuntu 22.04 LTS machine, I was not able to build via bazel.

It looks like the compiler is not finding any standard includes:
```
➜ bazel build //...                
ERROR: /home/marksc7/dev/score/src/communication/score/mw/com/impl/bindings/lola/BUILD:524:11: Compiling score/mw/com/impl/bindings/lola/event_slot_status.cpp failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile command (from target //score/mw/com/impl/bindings/lola:event_slot_status) external/toolchains_llvm~~llvm~llvm_toolchain/bin/cc_wrapper.sh -U_FORTIFY_SOURCE '-march=nehalem' '-ffp-model=strict' -U_FORTIFY_SOURCE -fstack-protector -fno-omit-frame-pointer -fcolor-diagnostics ... (remaining 24 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from score/mw/com/impl/bindings/lola/event_slot_status.cpp:13:
./score/mw/com/impl/bindings/lola/event_slot_status.h:16:10: fatal error: 'cstdint' file not found
#include <cstdint>
         ^~~~~~~~~
1 error generated.
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.417s, Critical Path: 0.14s
INFO: 271 processes: 271 internal.
ERROR: Build did NOT complete successfully
FAILED: 
    Fetching module extension crate in @@rules_rust~//crate_universe:extensions.bzl; Splicing Cargo workspace for `crate_index`
```

After following @LittleHuba  tipp that it works on an Ubuntu 20.04 with llvm-16, I installed clang-16 and llvm in a docker container (Ubuntu 24.04) along with bazel and ncurses5 et cetera and with some modifications, it does seem to build successfully and I can run tests.

I also had to modify the baselibs ... https://github.com/eclipse-score/baselibs/commit/9498064967db802c76b631b1b53d72eaaebd462a ... which is probably not necessary with the correct toolchain / environment.

So, I really hope we can move towards a self-contained toolchain that relies less on the system around it.

**Comment by LittleHuba** [comment]
The problem of the current toolchain is, that it is not fully hermetic. This leads to the necessary system modifications.
Since @armin-acn pointed out a temporary workaround, I want to focus on an acutal fix that brings us closer to our goal of using the toolchain https://github.com/eclipse-score/toolchains_gcc/tree/main

Currently that toolchain is not quite where we need it since it has a libmqueue version with missing symbols.

I'm in contact with @nradakovic to fix this.

Should somebody not want to do the modifications on system level up till then, you should use a docker image as described by @MarkSchmitt.

A good starting point to the docker image can be seen from this PR done by @nradakovic for the baselibs:
https://github.com/nradakovic/baselibs/pull/2

**Comment by LittleHuba** [comment]
Toolchain fix is merged. Raised PR to add the new toolchain version to the bazel registry.
Once the registry is updated, I'll raise the PR to switch the communication module to the new toolchain.

**Comment by LittleHuba** [comment]
Toolchain is now updated to the S-CORE GCC 12.2 toolchain.

Fix merged with d96564ccb608fa4318d332b2384644d5ec31a21e
